# prometheus.yml - Configuración de Prometheus para monitoreo de Changánet
# @descripción Configuración de recolección de métricas del backend (REQ-41)
# @sprint Sprint 1 – Autenticación y Perfiles
# @tarjeta Tarjeta 1: [Infra] Configurar Monitoreo con Prometheus y Grafana
# @impacto Ambiental: Monitoreo eficiente que permite optimizar recursos del sistema

global:
  scrape_interval: 15s  # Intervalo de recolección de métricas
  evaluation_interval: 15s  # Intervalo de evaluación de reglas

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'changanet-backend'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']